apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpro
spec:
  selector:
    matchLabels:
      app: dpro
  template:
    metadata:
      labels:
        app: dpro
    spec:
      containers:
        - name: dpro
          image: dpro
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: dpro-config
            - secretRef:
                name: dpro-secret
